//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexTimeKeeper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public int logType { get; set; }
        public Nullable<int> logDirection { get; set; }
        public System.DateTime logDate { get; set; }
        public string logComment { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
