//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexTimeKeeper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTypeMapping
    {
        public int logTypeValue { get; set; }
        public string logTypeName { get; set; }
    }
}
