//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexTimeKeeper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlexTimeKeeperEntities : DbContext
    {
        public FlexTimeKeeperEntities()
            : base("name=FlexTimeKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogTypeMapping> LogTypeMappings { get; set; }
        public virtual DbSet<TimeKeeper> TimeKeepers { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
